'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'
import { Button } from '@/components/ui'
import { Download, Copy, Check } from 'lucide-react'
import type { SolarAnalysisAdvanced } from '@/types'

export interface AnalysisReportExportProps {
  result: SolarAnalysisAdvanced
}

const formatCurrency = (value: number): string =>
  new Intl.NumberFormat('th-TH', {
    style: 'currency',
    currency: 'THB',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)

const formatNumber = (value: number, decimals = 0): string =>
  new Intl.NumberFormat('th-TH', { maximumFractionDigits: decimals }).format(value)

function generateTextSummary(result: SolarAnalysisAdvanced): string {
  const lines: string[] = [
    '=== SolarIQ Analysis Report ===',
    '',
    `Location: ${result.address}`,
    `Coordinates: ${(result.coordinates.latitude ?? 0).toFixed(4)}, ${(result.coordinates.longitude ?? 0).toFixed(4)}`,
    '',
    '--- System Recommendation ---',
    `System Size: ${(result.panelConfig.capacityKw ?? 0).toFixed(2)} kWp`,
    `Number of Panels: ${result.panelConfig.panelsCount}`,
    `Yearly Production: ${formatNumber(result.panelConfig.yearlyEnergyDcKwh)} kWh`,
    '',
    '--- Financial Summary ---',
    `Installation Cost: ${formatCurrency(result.financialAnalysis.installationCost)}`,
    `Net Cost: ${formatCurrency(result.financialAnalysis.netCost)}`,
    `Monthly Savings: ${formatCurrency(result.financialAnalysis.monthlySavings)}`,
    `Yearly Savings: ${formatCurrency(result.financialAnalysis.yearlySavings)}`,
    `Payback Period: ${(result.financialAnalysis.paybackYears ?? 0).toFixed(1)} years`,
    `25-Year ROI: ${(result.financialAnalysis.roi25Year ?? 0).toFixed(1)}%`,
    `NPV (25-Year): ${formatCurrency(result.financialAnalysis.npvThb)}`,
    `IRR: ${(result.financialAnalysis.irrPercent ?? 0).toFixed(1)}%`,
  ]

  if (result.annualMaintenanceCost) {
    lines.push(`Annual Maintenance: ${formatCurrency(result.annualMaintenanceCost)}`)
  }

  if (result.selfConsumptionRate) {
    lines.push(`Self-Consumption Rate: ${(result.selfConsumptionRate * 100).toFixed(0)}%`)
  }

  if (result.netBillingRate) {
    lines.push(`Net Billing Rate: ${(result.netBillingRate ?? 0).toFixed(1)} THB/kWh`)
  }

  lines.push('', '--- Environmental Impact ---')

  if (result.environmentalImpact) {
    lines.push(
      `CO2 Offset/Year: ${formatNumber(result.environmentalImpact.co2OffsetTonsPerYear, 1)} tons`,
      `CO2 Offset (25-yr): ${formatNumber(result.environmentalImpact.co2OffsetTons25yr, 1)} tons`,
      `Trees Equivalent: ${formatNumber(result.environmentalImpact.treesEquivalent)}`,
      `Cars Off Road: ${formatNumber(result.environmentalImpact.carsOffRoad, 1)}`
    )
  }

  lines.push(
    '',
    '--- Solar Potential ---',
    `Max Sunshine Hours: ${formatNumber(result.solarPotential.maxSunshineHoursPerYear)} hrs/yr`,
    `Roof Area: ${(result.solarPotential.roofAreaM2 ?? 0).toFixed(0)} m2`,
    `Max Panels: ${result.solarPotential.maxPanels}`,
    `Quality: ${result.solarPotential.quality}`,
    '',
    `Electricity Rate: ${(result.electricityRate ?? 0).toFixed(2)} THB/kWh`,
    '',
    '=== Generated by SolarIQ ==='
  )

  return lines.join('\n')
}

function generatePrintHtml(result: SolarAnalysisAdvanced): string {
  const co2PerYear = result.environmentalImpact
    ? formatNumber(result.environmentalImpact.co2OffsetTonsPerYear, 1)
    : formatNumber(
        (result.panelConfig.yearlyEnergyDcKwh * result.solarPotential.carbonOffsetFactorKgPerMwh) /
          1000,
        1
      )

  return `<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SolarIQ Analysis Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      color: #1a1a2e;
      background: #fff;
      padding: 40px;
      line-height: 1.6;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #f97316;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 28px;
      color: #f97316;
      margin-bottom: 4px;
    }
    .header p {
      color: #666;
      font-size: 14px;
    }
    .section {
      margin-bottom: 24px;
      break-inside: avoid;
    }
    .section h2 {
      font-size: 18px;
      color: #f97316;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 6px;
      margin-bottom: 12px;
    }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px 24px;
    }
    .grid-4 {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
    }
    .item {
      padding: 4px 0;
    }
    .item .label {
      font-size: 12px;
      color: #888;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .item .value {
      font-size: 16px;
      font-weight: 600;
    }
    .item .value.highlight {
      color: #16a34a;
    }
    .item .value.primary {
      color: #f97316;
    }
    .stat-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 16px;
      text-align: center;
    }
    .stat-card .stat-value {
      font-size: 24px;
      font-weight: 700;
      color: #f97316;
    }
    .stat-card .stat-label {
      font-size: 12px;
      color: #666;
      margin-top: 4px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #999;
    }
    @media print {
      body { padding: 20px; }
      .no-print { display: none !important; }
      .section { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>SolarIQ Analysis Report</h1>
    <p>Solar Potential Analysis &amp; Financial Projection</p>
  </div>

  <div class="section">
    <h2>Location Information</h2>
    <div class="grid">
      <div class="item">
        <div class="label">Address</div>
        <div class="value">${result.address || 'N/A'}</div>
      </div>
      <div class="item">
        <div class="label">Coordinates</div>
        <div class="value">${(result.coordinates.latitude ?? 0).toFixed(4)}, ${(result.coordinates.longitude ?? 0).toFixed(4)}</div>
      </div>
      <div class="item">
        <div class="label">Electricity Rate</div>
        <div class="value">${(result.electricityRate ?? 0).toFixed(2)} THB/kWh</div>
      </div>
      <div class="item">
        <div class="label">Imagery Quality</div>
        <div class="value">${result.solarPotential.quality}</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>System Recommendation</h2>
    <div class="grid-4">
      <div class="stat-card">
        <div class="stat-value">${(result.panelConfig.capacityKw ?? 0).toFixed(2)}</div>
        <div class="stat-label">kWp System Size</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${result.panelConfig.panelsCount}</div>
        <div class="stat-label">Solar Panels</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${formatNumber(result.panelConfig.yearlyEnergyDcKwh)}</div>
        <div class="stat-label">kWh / Year</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${(result.solarPotential.roofAreaM2 ?? 0).toFixed(0)}</div>
        <div class="stat-label">m&sup2; Roof Area</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Financial Summary</h2>
    <div class="grid">
      <div class="item">
        <div class="label">Installation Cost</div>
        <div class="value">${formatCurrency(result.financialAnalysis.installationCost)}</div>
      </div>
      <div class="item">
        <div class="label">Net Cost (After Incentives)</div>
        <div class="value highlight">${formatCurrency(result.financialAnalysis.netCost)}</div>
      </div>
      <div class="item">
        <div class="label">Monthly Savings</div>
        <div class="value highlight">${formatCurrency(result.financialAnalysis.monthlySavings)}</div>
      </div>
      <div class="item">
        <div class="label">Yearly Savings</div>
        <div class="value highlight">${formatCurrency(result.financialAnalysis.yearlySavings)}</div>
      </div>
      <div class="item">
        <div class="label">Payback Period</div>
        <div class="value primary">${(result.financialAnalysis.paybackYears ?? 0).toFixed(1)} years</div>
      </div>
      <div class="item">
        <div class="label">25-Year ROI</div>
        <div class="value primary">${(result.financialAnalysis.roi25Year ?? 0).toFixed(1)}%</div>
      </div>
      <div class="item">
        <div class="label">NPV (25-Year)</div>
        <div class="value">${formatCurrency(result.financialAnalysis.npvThb)}</div>
      </div>
      <div class="item">
        <div class="label">IRR</div>
        <div class="value">${(result.financialAnalysis.irrPercent ?? 0).toFixed(1)}%</div>
      </div>
      ${
        result.annualMaintenanceCost
          ? `
      <div class="item">
        <div class="label">Annual Maintenance Cost</div>
        <div class="value">${formatCurrency(result.annualMaintenanceCost)}</div>
      </div>`
          : ''
      }
      ${
        result.selfConsumptionRate
          ? `
      <div class="item">
        <div class="label">Self-Consumption Rate</div>
        <div class="value">${(result.selfConsumptionRate * 100).toFixed(0)}%</div>
      </div>`
          : ''
      }
      ${
        result.netBillingRate
          ? `
      <div class="item">
        <div class="label">Net Billing Rate</div>
        <div class="value">${(result.netBillingRate ?? 0).toFixed(1)} THB/kWh</div>
      </div>`
          : ''
      }
    </div>
  </div>

  <div class="section">
    <h2>Environmental Impact</h2>
    <div class="grid-4">
      <div class="stat-card">
        <div class="stat-value">${co2PerYear}</div>
        <div class="stat-label">tons CO2 / year</div>
      </div>
      ${
        result.environmentalImpact
          ? `
      <div class="stat-card">
        <div class="stat-value">${formatNumber(result.environmentalImpact.treesEquivalent)}</div>
        <div class="stat-label">Trees Equivalent</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${formatNumber(result.environmentalImpact.carsOffRoad, 1)}</div>
        <div class="stat-label">Cars Off Road</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${formatNumber(result.environmentalImpact.co2OffsetTons25yr, 1)}</div>
        <div class="stat-label">tons CO2 (25-yr)</div>
      </div>`
          : ''
      }
    </div>
  </div>

  <div class="section">
    <h2>Solar Potential</h2>
    <div class="grid">
      <div class="item">
        <div class="label">Max Sunshine Hours</div>
        <div class="value">${formatNumber(result.solarPotential.maxSunshineHoursPerYear)} hrs/yr</div>
      </div>
      <div class="item">
        <div class="label">Max Panels Capacity</div>
        <div class="value">${result.solarPotential.maxPanels} panels</div>
      </div>
      <div class="item">
        <div class="label">Quality Rating</div>
        <div class="value primary">${result.solarPotential.quality}</div>
      </div>
      ${
        result.solarPotential.imageryDate
          ? `
      <div class="item">
        <div class="label">Imagery Date</div>
        <div class="value">${result.solarPotential.imageryDate}</div>
      </div>`
          : ''
      }
    </div>
  </div>

  <div class="footer">
    <p>Generated by SolarIQ &mdash; ${new Date().toLocaleDateString('th-TH', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    <p>This report is for reference purposes only. Actual results may vary.</p>
  </div>

  <script>
    window.onload = function() { window.print(); };
  </script>
</body>
</html>`
}

export function AnalysisReportExport({ result }: AnalysisReportExportProps) {
  const t = useTranslations('analysisReport')
  const [copied, setCopied] = useState(false)

  const handlePrintReport = () => {
    const html = generatePrintHtml(result)
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(html)
      printWindow.document.close()
    }
  }

  const handleCopyReport = async () => {
    const text = generateTextSummary(result)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea')
      textarea.value = text
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="primary"
        size="sm"
        onClick={handlePrintReport}
        leftIcon={<Download className="w-4 h-4" />}
      >
        {t('downloadPdf')}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleCopyReport}
        leftIcon={
          copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />
        }
      >
        {copied ? t('exporting') : t('shareReport')}
      </Button>
    </div>
  )
}
